Neos:
  Neos:
    Ui:
      resources:
        stylesheets:
          Shel.Neos:HyphensEditor:
            resource: resource://Shel.Neos.Hyphens/Public/HyphensEditor/Plugin.css
        javascript:
          Shel.Neos:HyphensEditor:
            resource: resource://Shel.Neos.Hyphens/Public/HyphensEditor/Plugin.js

    fusion:
      autoInclude:
        Shel.Neos.Hyphens: true

    userInterface:
      translation:
        autoInclude:
          Shel.Neos.Hyphens:
            - 'Main'
